version: '3'

services:
  mariadb:
    image: mariadb:10.6
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - abuse

  php8:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - abuse
    depends_on:
      - mariadb

networks:
  abuse: