version: '3'

services:
  mariadb:
    image: mariadb:10.6
    environment: 
      - MARIADB_ROOT_PASSWORD=password
    networks:
      - abuse

  php7.4:
    build:
      context: .
      dockerfile: ./Dockerfile-php7
    networks:
      - abuse
    depends_on:
      - mariadb

  php8:
    build:
      context: .
      dockerfile: ./Dockerfile-php8
    networks:
      - abuse
    depends_on:
      - mariadb

networks:
  abuse: